application: tensile-runway-92512
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
